baseURL = "https://mijux.github.io/"
languageCode = "en-us"
title = "Mijux's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Mijux"
  description = "In solitude, where we are least alone."
  github = "Username"
  facebook = "Username"
  twitter = "Username"
  linkedin = "Username"
  instagram = "Username"
  tumblr = "Username"
  email = "your.email@domain.com"
  url = "https://mijux.github.io"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "USA"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = true
  
  googleanalytics = "UA-******-***"
  mamotoserver = "your.mamoto.instance"
  mamotoid = "your_website_id_on_mamoto"


  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "ventusoon" # æ‚¨çš„GitHub ID
    admin = "ventusoon" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  [[params.links]]
    title = "Link"
    href = "https://github.com/Mijux"
  [[params.links]]
    title = "Link2"
    href = "https://mijux.github.io"
    icon = "https://mijux.github.io/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
